CREATE TABLE IF NOT EXISTS editbot_prompt_favorites (
  user_id BIGINT UNSIGNED NOT NULL,
  prompt_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, prompt_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
