version: "2"

linters:
  enable:
    - errcheck
    - govet
    - importas
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  importas:
    no-unaliased: false
    no-extra-aliases: true
    alias:
      - pkg: github.com/redis/go-redis/v9
        alias: goredis
      - pkg: github.com/zetaoss/zengine/goapp/app/redis
        alias: appredis
      - pkg: github.com/zetaoss/zengine/goapp/models/stat
        alias: statmodels
