version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    # - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    # - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    # - goconst
    - gocritic
    - gocyclo
    - godox
    # - mnd
    - goprintffuncname
    # - gosec
    - govet
    - importas
    - intrange
    - ineffassign
    # - lll
    - misspell
    - nakedret
    # - noctx
    - nolintlint
    # - revive
    - staticcheck
    - testifylint
    - unconvert
    # - unparam
    - unused
    - whitespace

linters-settings:
  importas:
    no-unaliased: false
    no-extra-aliases: true
    alias:
      - pkg: github.com/redis/go-redis/v9
        alias: goredis
      - pkg: github.com/zetaoss/zengine/goapp/app/redis
        alias: appredis
      - pkg: github.com/zetaoss/zengine/goapp/models/stat
        alias: statmodels
